/**
 * @file    main.c
 * @brief   MOD-01 Main Application — Full System Integration
 * @author  Grup 7
 * @date    2026-05-16
 * @version 1.0
 *
 * Description:
 *   Top-level application that initialises and orchestrates all MOD-01
 *   subsystems in a single super-loop:
 *
 *     1. Power Management  — 12V Decoy enable + 60-min RTH failsafe
 *     2. UART Communication — Telemetry TX + Command RX with Raspberry Pi 5
 *     3. Motor Control     — L298N 4WD differential drive
 *     4. Stuck Detection   — MPU6050 IMU-based stuck/recovery FSM
 *     5. Environment Sensors — DHT22 + MQ-2 periodic reads
 *
 *   Timing:
 *     - Motor commands:     processed immediately via UART RX (interrupt-driven)
 *     - Stuck detection:    every 100 ms
 *     - Environment sensors: every 2000 ms (DHT22 minimum interval)
 *     - Telemetry broadcast: every 500 ms
 *     - Power failsafe:     every 1000 ms
 */

#include "pwr_management.h"
#include "uart_comm.h"
#include "motor_control.h"
#include "stuck_detection.h"
#include "environment_sensors.h"
#include "stm32f4xx_hal.h"

/* ===== External HAL Handles (generated by CubeMX) ======================= */

extern UART_HandleTypeDef huart2;
extern I2C_HandleTypeDef  hi2c1;
extern TIM_HandleTypeDef  htim3;

/* ===== CubeMX Init Prototypes =========================================== */

void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_USART2_UART_Init(void);
void MX_I2C1_Init(void);
void MX_TIM3_Init(void);
void MX_ADC1_Init(void);
void Error_Handler(void);

/* ===== Global Instances ================================================= */

static MotorControl_t    g_motor;
static StuckDetection_t  g_stuck;
static environment_data_t g_env_data;
static uart_telemetry_t  g_telemetry;
static uart_command_t    g_last_cmd;

/* ===== Timing Constants (ms) ============================================ */

#define TICK_STUCK_DETECTION_MS    100
#define TICK_ENV_SENSOR_MS         2000
#define TICK_TELEMETRY_TX_MS       500
#define TICK_POWER_CHECK_MS        1000

/* ===== Subsystem Init =================================================== */

/**
 * @brief  Initialise all MOD-01 subsystems.
 *         Any failure triggers Error_Handler().
 */
static void System_Init(void)
{
    /* 1. Power Management */
    if (pwr_init() != PWR_STATUS_OK) {
        Error_Handler();
    }
    pwr_set_decoy_state(true);  /* Enable 12V for motors */

    /* 2. UART Communication */
    if (uart_comm_init() != 0) {
        Error_Handler();
    }

    /* 3. Motor Control */
    MotorConfig_t motor_cfg = {
        .motorA_IN1_port    = GPIOA,
        .motorA_IN1_pin     = GPIO_PIN_0,
        .motorA_IN2_port    = GPIOA,
        .motorA_IN2_pin     = GPIO_PIN_1,
        .motorB_IN3_port    = GPIOA,
        .motorB_IN3_pin     = GPIO_PIN_4,
        .motorB_IN4_port    = GPIOA,
        .motorB_IN4_pin     = GPIO_PIN_5,
        .pwm_timer          = &htim3,
        .motorA_pwm_channel = TIM_CHANNEL_1,
        .motorB_pwm_channel = TIM_CHANNEL_2
    };
    if (Motor_Init(&g_motor, &motor_cfg) != HAL_OK) {
        Error_Handler();
    }
    Motor_SetSpeed(&g_motor, 70);  /* Default cruising speed 70% */

    /* 4. Stuck Detection (MPU6050 over I2C) */
    if (StuckDetection_Init(&g_stuck, &hi2c1, &g_motor) != HAL_OK) {
        Error_Handler();
    }

    /* 5. Environment Sensors (DHT22 + MQ-2) */
    if (env_sensors_init() != ENV_SENSOR_OK) {
        /* Non-critical — log warning but don't halt */
    }

    /* Zero out state */
    memset(&g_env_data,  0, sizeof(g_env_data));
    memset(&g_telemetry, 0, sizeof(g_telemetry));
    memset(&g_last_cmd,  0, sizeof(g_last_cmd));
}

/* ===== Task Functions =================================================== */

/**
 * @brief  Process incoming UART commands and drive motors.
 *         Called every main loop iteration (non-blocking).
 */
static void Task_ProcessCommands(void)
{
    uart_command_t cmd;
    if (uart_receive_command(&cmd)) {
        g_last_cmd = cmd;

        /* Don't override motors if stuck recovery is in progress */
        if (!StuckDetection_IsRecovering(&g_stuck)) {
            Motor_ExecuteCommand(&g_motor, (MotorCommand_t)cmd.direction);
            Motor_SetSpeed(&g_motor, cmd.speed_pwm * 100 / 255);

            /* TODO: Handle buzzer_on and lights_on GPIO toggling */
        }
    }
}

/**
 * @brief  Run stuck detection FSM tick.
 */
static void Task_StuckDetection(void)
{
    StuckDetection_Task(&g_stuck);
}

/**
 * @brief  Read environment sensors (DHT22 + MQ-2).
 */
static void Task_ReadEnvironment(void)
{
    env_read_all(&g_env_data);
}

/**
 * @brief  Populate and transmit telemetry packet to Pi 5.
 */
static void Task_SendTelemetry(void)
{
    g_telemetry.temperature    = g_env_data.temperature_c;
    g_telemetry.smoke_detected = g_env_data.smoke_alert;
    g_telemetry.is_stuck       = (StuckDetection_GetState(&g_stuck) == STUCK_STATE_CONFIRMED ||
                                  StuckDetection_GetState(&g_stuck) == STUCK_STATE_RECOVERING);
    /* Acoustic angle is set by MOD-03 firmware — leave as-is unless updated */
    /* g_telemetry.acoustic_angle = ...; */

    /* IMU yaw — get from stuck detection module's IMU data */
    /* g_telemetry.imu_yaw_angle = imu_get_yaw_angle(); */

    /* Ultrasonic distances — placeholder until HC-SR04 driver is added */
    /* g_telemetry.us_dist_front = ...; */

    uart_send_telemetry(&g_telemetry);
}

/**
 * @brief  Check power failsafes and trigger RTH if needed.
 */
static void Task_PowerCheck(void)
{
    /* 60-minute timeout */
    if (pwr_is_time_limit_exceeded()) {
        /* Emergency stop + signal RTH to Pi */
        Motor_EmergencyStop(&g_motor);
        pwr_set_decoy_state(false);

        /* Send a final telemetry burst indicating time-limit hit */
        g_telemetry.is_stuck = true;  /* Abuse stuck flag as "halted" */
        uart_send_telemetry(&g_telemetry);

        /* Halt — in a production system this would trigger RTH FSM */
        while (1) {
            HAL_Delay(1000);
        }
    }

    /* Pi power loss check (optional, if pwr_is_pi_alive is available) */
    /* if (!pwr_is_pi_alive()) { Motor_EmergencyStop(&g_motor); } */
}

/* ===== Main ============================================================= */

int main(void)
{
    /* ---- HAL + Peripheral Init (CubeMX generated) ---- */
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_I2C1_Init();
    MX_TIM3_Init();
    MX_ADC1_Init();

    /* ---- MOD-01 Subsystem Init ---- */
    System_Init();

    /* ---- Timing Trackers ---- */
    uint32_t last_stuck_ms     = 0;
    uint32_t last_env_ms       = 0;
    uint32_t last_telemetry_ms = 0;
    uint32_t last_power_ms     = 0;

    /* ---- Super-Loop ---- */
    while (1)
    {
        uint32_t now = HAL_GetTick();

        /* Always: check for incoming UART commands (non-blocking) */
        Task_ProcessCommands();

        /* Every 100ms: stuck detection */
        if ((now - last_stuck_ms) >= TICK_STUCK_DETECTION_MS) {
            Task_StuckDetection();
            last_stuck_ms = now;
        }

        /* Every 2s: environment sensors */
        if ((now - last_env_ms) >= TICK_ENV_SENSOR_MS) {
            Task_ReadEnvironment();
            last_env_ms = now;
        }

        /* Every 500ms: telemetry broadcast */
        if ((now - last_telemetry_ms) >= TICK_TELEMETRY_TX_MS) {
            Task_SendTelemetry();
            last_telemetry_ms = now;
        }

        /* Every 1s: power failsafe checks */
        if ((now - last_power_ms) >= TICK_POWER_CHECK_MS) {
            Task_PowerCheck();
            last_power_ms = now;
        }
    }
}

/* ===== Error Handler ==================================================== */

void Error_Handler(void)
{
    /* Emergency stop all motors */
    Motor_EmergencyStop(&g_motor);
    pwr_set_decoy_state(false);

    /* Infinite loop — blink an LED or trigger watchdog in production */
    __disable_irq();
    while (1) {
    }
}
